# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/ViennaRNA
pkgincludedir = $(includedir)/ViennaRNA
pkglibdir = $(libdir)/ViennaRNA
pkglibexecdir = $(libexecdir)/ViennaRNA
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ac_rna.m4 \
	$(top_srcdir)/m4/ac_rna_build_requirements.m4 \
	$(top_srcdir)/m4/ac_rna_cla.m4 \
	$(top_srcdir)/m4/ac_rna_colorize.m4 \
	$(top_srcdir)/m4/ac_rna_features.m4 \
	$(top_srcdir)/m4/ac_rna_latex.m4 \
	$(top_srcdir)/m4/ac_rna_lto.m4 \
	$(top_srcdir)/m4/ac_rna_macros.m4 \
	$(top_srcdir)/m4/ac_rna_osx.m4 \
	$(top_srcdir)/m4/ac_rna_refman.m4 \
	$(top_srcdir)/m4/ac_rna_subpackages.m4 \
	$(top_srcdir)/m4/ac_rna_swig.m4 \
	$(top_srcdir)/m4/ac_rna_tutorial.m4 \
	$(top_srcdir)/m4/ac_rna_unit_tests.m4 \
	$(top_srcdir)/m4/ax_append_flag.m4 \
	$(top_srcdir)/m4/ax_check_compile_flag.m4 \
	$(top_srcdir)/m4/ax_check_link_flag.m4 \
	$(top_srcdir)/m4/ax_compiler_vendor.m4 \
	$(top_srcdir)/m4/ax_cxx_compile_stdcxx.m4 \
	$(top_srcdir)/m4/ax_openmp.m4 $(top_srcdir)/m4/ax_perl_ext.m4 \
	$(top_srcdir)/m4/ax_pkg_swig.m4 $(top_srcdir)/m4/ax_pthread.m4 \
	$(top_srcdir)/m4/ax_python2_devel.m4 \
	$(top_srcdir)/m4/ax_python3_devel.m4 \
	$(top_srcdir)/m4/ax_require_defined.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = packaging/macosx/resources/welcome.txt \
	interfaces/Python/RNA/__init__.py setup.py setup.cfg \
	pyproject.toml ${DOXYGEN_DOCDIR}/${DOXYGEN_CONF} \
	${SPHINX_SRCDIR}/conf.py ${SPHINX_SRCDIR}/install.rst \
	RNAlib2.pc packaging/viennarna.spec packaging/PKGBUILD \
	packaging/win_installer_archlinux_i686.nsi \
	packaging/win_installer_archlinux_x86_64.nsi \
	packaging/win_installer_fedora_i686.nsi \
	packaging/win_installer_fedora_x86_64.nsi
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(pkgconfigdir)"
DATA = $(pkgconfig_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/RNAlib2.pc.in \
	$(srcdir)/config.h.in $(srcdir)/pyproject.toml.in \
	$(srcdir)/setup.cfg.in $(srcdir)/setup.py.in \
	$(top_srcdir)/${DOXYGEN_DOCDIR}/${DOXYGEN_CONF}.in \
	$(top_srcdir)/${SPHINX_SRCDIR}/conf.py.in \
	$(top_srcdir)/${SPHINX_SRCDIR}/install.rst.in \
	$(top_srcdir)/config/ar-lib $(top_srcdir)/config/compile \
	$(top_srcdir)/config/config.guess \
	$(top_srcdir)/config/config.sub \
	$(top_srcdir)/config/install-sh $(top_srcdir)/config/ltmain.sh \
	$(top_srcdir)/config/missing \
	$(top_srcdir)/config/tap-driver.sh \
	$(top_srcdir)/interfaces/Python/RNA/__init__.py.in \
	$(top_srcdir)/packaging/PKGBUILD.in \
	$(top_srcdir)/packaging/macosx/resources/welcome.txt.in \
	$(top_srcdir)/packaging/viennarna.spec.in \
	$(top_srcdir)/packaging/win_installer_archlinux_i686.nsi.in \
	$(top_srcdir)/packaging/win_installer_archlinux_x86_64.nsi.in \
	$(top_srcdir)/packaging/win_installer_fedora_i686.nsi.in \
	$(top_srcdir)/packaging/win_installer_fedora_x86_64.nsi.in \
	AUTHORS COPYING INSTALL NEWS THANKS config/ar-lib \
	config/compile config/config.guess config/config.sub \
	config/depcomp config/install-sh config/ltmain.sh \
	config/missing config/texinfo.tex
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_CFLAGS = 
AM_CPPFLAGS = 
AM_CXXFLAGS = 
AM_DEFAULT_VERBOSITY = 0
AM_LDFLAGS = 
AR = ar
AUTOCONF = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/missing autoconf
AUTOHEADER = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/missing autoheader
AUTOMAKE = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/missing automake-1.16
AWK = gawk
BIBTEX_CMD = no
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CHECK_CFLAGS = 
CHECK_LIBS = 
CLA_CMD_LATEX = no -interaction=nonstopmode -halt-on-error
CLA_DOCDIR = doc/CLA
CLA_E_PDF_NAME = ViennaRNA-CLA-Entity.pdf
CLA_E_PROJECT_NAME = ViennaRNA-CLA-Entity
CLA_I_PDF_NAME = ViennaRNA-CLA-Individual.pdf
CLA_I_PROJECT_NAME = ViennaRNA-CLA-Individual
CLA_SRCDIR = .
CLUSTER_DIR = 
CONFIG_DISABLE_C11_FEATURES = 
CONFIG_FLOAT_PF = 
CONFIG_GSL = 
CONFIG_LTO = 
CONFIG_NAVIEW_LAYOUT = #define VRNA_WITH_NAVIEW_LAYOUT
CONFIG_NR_SAMPLING = 
CONFIG_OPENMP = #define VRNA_WITH_OPENMP
CONFIG_SVM = #define VRNA_WITH_SVM
CONFIG_TTY_COLORS = 
CPP = gcc -E
CPPFLAGS = 
CXX = g++ -std=c++17
CXXCPP = g++ -E -std=c++17
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DEPRECATION_WARNING = 
DIFF = /usr/bin/diff
DISABLE_C11_FEATURES = 
DLIB_CPPFLAGS = -I$(top_srcdir)/src/dlib-19.24 -DDLIB_NO_GUI_SUPPORT
DLIB_DIR = dlib-19.24
DLIB_VERSION = 19.24
DLLTOOL = false
DOXYGEN_CONF = doxygen.conf
DOXYGEN_DOCDIR = doc/doxygen
DOXYGEN_HAVE_DOT = YES
DOXYGEN_PROJECT_NAME = RNAlib-2.6.4
DOXYGEN_SRCDIR = .
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = f77
FFLAGS = -g -O2
FGREP = /usr/bin/grep -F
FLOAT_PF_FLAG = 
GENGETOPT = /usr/bin/gengetopt
GREP = /usr/bin/grep
GSL_LIBS = 
HAVE_CXX17 = 1
HDIUTIL = 
HELP2MAN = /usr/bin/help2man
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
ISODATE = 2024-08-09
LATEX_CMD = no
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBGOMPFLAG = -fopenmp
LIBOBJS = 
LIBS = -lm 
LIBSVM_DIR = libsvm-3.31
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = config/ltmain.sh
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LTO_CFLAGS = -flto=auto -ffat-lto-objects
LTO_CXXFLAGS = -flto=auto -ffat-lto-objects
LTO_LDFLAGS = -flto=auto
LT_SYS_LIBRARY_PATH = 
MACOSX_INSTALLER = 
MAKEINDEX_CMD = no
MAKEINFO = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
MPFR_LIBS = 
NAVIEW_DIR = plotting/naview
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OPENMP_CFLAGS = -fopenmp
OPENMP_CXXFLAGS = -fopenmp
OTOOL = 
OTOOL64 = 
OUR_AR = 
OUR_NM = 
OUR_RANLIB = 
PACKAGE = ViennaRNA
PACKAGE_BUGREPORT = rna@tbi.univie.ac.at
PACKAGE_NAME = ViennaRNA
PACKAGE_STRING = ViennaRNA 2.6.4
PACKAGE_TARNAME = ViennaRNA
PACKAGE_URL = https://www.tbi.univie.ac.at/RNA
PACKAGE_VERSION = 2.6.4
PARAMETER_FILES = misc/dna_mathews1999.par misc/dna_mathews2004.par misc/rna_andronescu2007.par misc/rna_langdon2018.par misc/rna_misc_special_hairpins.par misc/rna_turner1999.par misc/rna_turner2004.par misc/rna_mod_7DA_parameters.json misc/rna_mod_inosine_parameters.json misc/rna_mod_m6A_parameters.json misc/rna_mod_pseudouridine_parameters.json misc/rna_mod_purine_parameters.json misc/rna_mod_dihydrouridine_parameters.json 
PARAMETER_FILES_HEX = misc/dna_mathews1999.hex misc/dna_mathews2004.hex misc/rna_andronescu2007.hex misc/rna_langdon2018.hex misc/rna_misc_special_hairpins.hex misc/rna_turner1999.hex misc/rna_turner2004.hex misc/rna_mod_7DA_parameters.hex misc/rna_mod_inosine_parameters.hex misc/rna_mod_m6A_parameters.hex misc/rna_mod_pseudouridine_parameters.hex misc/rna_mod_purine_parameters.hex misc/rna_mod_dihydrouridine_parameters.hex 
PATH_SEPARATOR = :
PERL = /data/ntc/Software/miniconda3/envs/NTC/bin/perl
PERL_ARCH_RELATIVE_INSTALL_DIR = /lib/perl5/5.32/site_perl
PERL_EXT_CPPFLAGS = --sysroot=./..//x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D_GNU_SOURCE -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data/ntc/Software/miniconda3/envs/NTC/include -fdebug-prefix-map=/croot/perl_1667420799860/work=/usr/local/src/conda/perl-5.32.1 -fdebug-prefix-map=/data/ntc/Software/miniconda3/envs/NTC=/usr/local/src/conda-prefix -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2
PERL_EXT_INC = /data/ntc/Software/miniconda3/envs/NTC/lib/perl5/5.32/core_perl/CORE
PERL_EXT_LDFLAGS = -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/data/ntc/Software/miniconda3/envs/NTC/lib -Wl,-rpath-link,/data/ntc/Software/miniconda3/envs/NTC/lib -L/data/ntc/Software/miniconda3/envs/NTC/lib --sysroot=./..//x86_64-conda-linux-gnu/sysroot -fstack-protector-strong
PERL_EXT_LIB = .../../lib/perl5/5.32/site_perl
PERL_EXT_PREFIX = .../..
PERL_EXT_SITEARCH = .../../lib/perl5/5.32/site_perl
PERL_EXT_SITELIB = .../../lib/perl5/site_perl
PERL_EXT_SITEPREFIX = .../..
PERL_EXT_VENDORARCH = .../../lib/perl5/5.32/vendor_perl
PERL_EXT_VENDORLIB = .../../lib/perl5/vendor_perl
PERL_EXT_VENDORPREFIX = /data/ntc/Software/miniconda3/envs/NTC
PERL_INTERFACE = Perl
PERL_LIB_RELATIVE_INSTALL_DIR = /lib/perl5/site_perl
PERL_SO = .so
PKGBUILD = 
PKGPYEXEC2DIR = 
PKGPYTHON2DIR = 
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POW_LIB = 
PRODUCTBUILD = 
PS_TEMPLATE_FILES = postscript/structure_plot_macro_base.ps postscript/structure_plot_macro_extras.ps postscript/dot_plot_macro_base.ps postscript/dot_plot_macro_turn.ps postscript/dot_plot_macro_sd.ps postscript/dot_plot_macro_ud.ps postscript/dot_plot_macro_sc_motifs.ps postscript/dot_plot_macro_linear_data.ps postscript/aln_macro_base.ps 
PS_TEMPLATE_FILES_HEX = postscript/structure_plot_macro_base.hex postscript/structure_plot_macro_extras.hex postscript/dot_plot_macro_base.hex postscript/dot_plot_macro_turn.hex postscript/dot_plot_macro_sd.hex postscript/dot_plot_macro_ud.hex postscript/dot_plot_macro_sc_motifs.hex postscript/dot_plot_macro_linear_data.hex postscript/aln_macro_base.hex 
PTHREAD_CC = gcc
PTHREAD_CFLAGS = -pthread
PTHREAD_CXX = g++
PTHREAD_LIBS = -lpthread
PYEXEC2DIR = 
PYTHON2 = 
PYTHON2DIR = 
PYTHON2_DIR = 
PYTHON2_EXECDIR = 
PYTHON2_INC = 
PYTHON2_INTERFACE = 
PYTHON2_LD = 
PYTHON2_LDFLAGS = 
PYTHON2_SO = 
PYTHON3 = /data/ntc/Software/miniconda3/envs/NTC/bin/python3
PYTHON3_CACHE_OPT1_EXT = cpython-312.opt-1.pyc
PYTHON3_CACHE_TAG = cpython-312
PYTHON3_DIR = ${prefix}/lib/python3.12/site-packages
PYTHON3_EXECDIR = ${exec_prefix}/lib/python3.12/site-packages
PYTHON3_INC = /data/ntc/Software/miniconda3/envs/NTC/include/python3.12
PYTHON3_LD = gcc -pthread -B /data/ntc/Software/miniconda3/envs/NTC/compiler_compat -shared  -Wl,--allow-shlib-undefined -Wl,-rpath,/data/ntc/Software/miniconda3/envs/NTC/lib -Wl,-rpath-link,/data/ntc/Software/miniconda3/envs/NTC/lib -L/data/ntc/Software/miniconda3/envs/NTC/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/data/ntc/Software/miniconda3/envs/NTC/lib -Wl,-rpath-link,/data/ntc/Software/miniconda3/envs/NTC/lib -L/data/ntc/Software/miniconda3/envs/NTC/lib
PYTHON3_LDFLAGS = 
PYTHON3_SO = .cpython-312-x86_64-linux-gnu.so
PYTHON_INTERFACE = Python
RANLIB = ranlib
REFDOC_PREDEF_FLOAT_PF = 
REFDOC_PREDEF_SVM = VRNA_WITH_SVM
REFERENCE_MANUAL_PDF_NAME = RNAlib-2.6.4.pdf
REFERENCE_MANUAL_TAGFILE = RNAlib-2.6.4.tag
RNA_CFLAGS = -fno-strict-aliasing -fopenmp -ftree-vectorize
RNA_CPPFLAGS = -DVRNA_WITH_NAVIEW_LAYOUT
RNA_CXXFLAGS = -fno-strict-aliasing -fopenmp
RNA_LDFLAGS = -fno-strict-aliasing
SED = /usr/bin/sed
SETUPCFG_GSL_LIBS = 
SETUPCFG_GSL_MACRO = 
SETUPCFG_MPFR_LIBS = 
SETUPCFG_MPFR_MACRO = 
SETUPCFG_NAVIEW_MACRO = naview_macro  = VRNA_WITH_NAVIEW_LAYOUT
SETUPCFG_OPENMP_FLAGS = openmp_cflags = -fopenmp
SETUPCFG_OPENMP_MACRO = openmp_macro  = VRNA_WITH_OPENMP
SETUPCFG_SVM_LIBS = svm_libs  = stdc++
SETUPCFG_SVM_MACRO = svm_macro = VRNA_WITH_SVM
SETUPCFG_SW_GSL = False
SETUPCFG_SW_MPFR = False
SETUPCFG_SW_NAVIEW = True
SETUPCFG_SW_OPENMP = True
SETUPCFG_SW_SIMD = True
SETUPCFG_SW_SVM = True
SET_MAKE = 
SHELL = /bin/bash
SIMD_AVX512_FLAGS = -mavx512f
SIMD_SSE41_FLAGS = -msse4.1
SPHINXBUILD = no
SPHINX_CMD_BIBTEX = no
SPHINX_CMD_LATEX = no -interaction=nonstopmode -halt-on-error
SPHINX_CMD_MAKEINDEX = no
SPHINX_SRCDIR = doc/source
STRIP = strip
SVG_TEMPLATE_FILES = svg/structure_plot_header.svg svg/structure_plot_footer.svg 
SVG_TEMPLATE_FILES_HEX = svg/structure_plot_header.hex svg/structure_plot_footer.hex 
SVM_LIBS = -lstdc++
SVM_VERSION = 3.31
SWIG = 
SWIG_LIB = 
TUTORIAL_CMD_HTLATEX = 
TUTORIAL_CMD_LATEX = no -interaction=nonstopmode -halt-on-error
TUTORIAL_DOCDIR = RNA-Tutorial
TUTORIAL_PDF_NAME = RNA-tutorial-2.6.4.pdf
TUTORIAL_PROJECT_NAME = RNA-tutorial-2.6.4
TUTORIAL_SRCDIR = .
USER_AR = 
USER_NM = 
USER_RANLIB = 
VERSION = 2.6.4
VRNA_CFLAGS =  -I$(top_srcdir)/../../src/ViennaRNA -I$(top_srcdir)/../../src -DVRNA_WITH_NAVIEW_LAYOUT
VRNA_LIBS =  -fno-strict-aliasing -L$(top_builddir)/../../src/ViennaRNA -lRNA -fopenmp  -lpthread  -lstdc++
VRNA_VERSION_MAJOR = 2
VRNA_VERSION_MINOR = 6
VRNA_VERSION_PATCH = 4
XXD = /usr/bin/xxd
abs_builddir = /data/ntc/Repository/ViennaRNA-2.6.4_make
abs_srcdir = /data/ntc/Repository/ViennaRNA-2.6.4_make
abs_top_builddir = /data/ntc/Repository/ViennaRNA-2.6.4_make
abs_top_srcdir = /data/ntc/Repository/ViennaRNA-2.6.4_make
ac_ct_AR = 
ac_ct_CC = gcc
ac_ct_CXX = 
ac_ct_DUMPBIN = 
ac_ct_F77 = f77
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
am__v_CCLD_0 = @[ -t 1 ] && printf "  \033[01;34mCCLD\033[00m     %s\n" $@ || echo "  CCLD     $@";
am__v_CC_0 = @[ -t 1 ] && printf "  \033[01;34mCC\033[00m       %s\n" $@ || echo "  CC       $@";
am__v_CXXLD_0 = @[ -t 1 ] && printf "  \033[01;34mCXXLD\033[00m    %s\n" $@ || echo "  CXXLD    $@";
am__v_CXX_0 = @[ -t 1 ] && printf "  \033[01;34mCXX\033[00m      %s\n" $@ || echo "  CXX      $@";
am__v_GEN_0 = @[ -t 1 ] && printf "  \033[01;34mGEN\033[00m      %s\n" $@ || echo "  GEN      $@";
ax_pthread_config = 
bibtex = no
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dot = /usr/bin/dot
doxygen = no
dvidir = ${docdir}
exec_prefix = ${prefix}
grep = /usr/bin/grep
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htlatex = no
htmldir = ${datarootdir}/doc/${PACKAGE_TARNAME}/html
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /data/ntc/Repository/ViennaRNA-2.6.4_make/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
makeindex = no
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
pdflatex = no
perl = /data/ntc/Software/miniconda3/envs/NTC/bin/perl
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
py2execdir = 
py3execdir = ${exec_prefix}/lib/python3.12/site-packages
python2dir = 
python3dir = ${prefix}/lib/python3.12/site-packages
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  src/Kinfold src/RNAforester src/RNAlocmin
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign subdir-objects
ACLOCAL_AMFLAGS = -I m4
AM_DISTCHECK_CONFIGURE_FLAGS = \
    --with-cluster \
    --without-forester \
    --with-kinwalker \
    --disable-silent-rules

SUBDIRS = \
    src \
    man \
    misc \
    doc/doxygen \
    interfaces \
    doc \
    RNA-Tutorial \
     src/Kinfold src/RNAforester src/RNAlocmin \
    tests \
    examples \
    packaging/macosx

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = RNAlib2.pc
EXTRA_DIST = packaging/debian \
              packaging/make_windows_installer.sh \
              license.txt \
              README.md \
              CHANGELOG.md \
              MANIFEST.in \
              silent_rules.mk

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
packaging/macosx/resources/welcome.txt: $(top_builddir)/config.status $(top_srcdir)/packaging/macosx/resources/welcome.txt.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
interfaces/Python/RNA/__init__.py: $(top_builddir)/config.status $(top_srcdir)/interfaces/Python/RNA/__init__.py.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
setup.py: $(top_builddir)/config.status $(srcdir)/setup.py.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
setup.cfg: $(top_builddir)/config.status $(srcdir)/setup.cfg.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
pyproject.toml: $(top_builddir)/config.status $(srcdir)/pyproject.toml.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
${DOXYGEN_DOCDIR}/${DOXYGEN_CONF}: $(top_builddir)/config.status $(top_srcdir)/${DOXYGEN_DOCDIR}/${DOXYGEN_CONF}.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
${SPHINX_SRCDIR}/conf.py: $(top_builddir)/config.status $(top_srcdir)/${SPHINX_SRCDIR}/conf.py.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
${SPHINX_SRCDIR}/install.rst: $(top_builddir)/config.status $(top_srcdir)/${SPHINX_SRCDIR}/install.rst.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
RNAlib2.pc: $(top_builddir)/config.status $(srcdir)/RNAlib2.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/viennarna.spec: $(top_builddir)/config.status $(top_srcdir)/packaging/viennarna.spec.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/PKGBUILD: $(top_builddir)/config.status $(top_srcdir)/packaging/PKGBUILD.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/win_installer_archlinux_i686.nsi: $(top_builddir)/config.status $(top_srcdir)/packaging/win_installer_archlinux_i686.nsi.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/win_installer_archlinux_x86_64.nsi: $(top_builddir)/config.status $(top_srcdir)/packaging/win_installer_archlinux_x86_64.nsi.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/win_installer_fedora_i686.nsi: $(top_builddir)/config.status $(top_srcdir)/packaging/win_installer_fedora_i686.nsi.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
packaging/win_installer_fedora_x86_64.nsi: $(top_builddir)/config.status $(top_srcdir)/packaging/win_installer_fedora_x86_64.nsi.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(DATA) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(pkgconfigdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-hdr \
	distclean-libtool distclean-local distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am:

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic \
	maintainer-clean-local

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-pkgconfigDATA

.MAKE: $(am__recursive_targets) all install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	clean-libtool cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-generic \
	distclean-hdr distclean-libtool distclean-local distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pkgconfigDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic \
	maintainer-clean-local mostlyclean mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-pkgconfigDATA

.PRECIOUS: Makefile


############################################
# Override 'distdir' automake rule to make
# sure that we build the reference manual
# including the Python documentation whenever
# we run 'make dist' and alike.
# For that, sphinx requires a working Python
# wrapper to RNAlib, which we need to build
# first. After that, we clean up the source
# tree again and continue with the regular
# 'distdir-am' rule.
############################################
distdir: $(BUILT_SOURCES)
	((test -f doc/refman-html && test -f doc/RNAlib-2.6.4.pdf) || \
  (cd src/ViennaRNA && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../../man && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../doc/doxygen && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../source/man && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../../../interfaces/Python && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../../doc && $(MAKE) $(AM_MAKEFLAGS) && \
  cd ../interfaces/Python && $(MAKE) $(AM_MAKEFLAGS) clean && \
  cd ../../src/ViennaRNA && $(MAKE) $(AM_MAKEFLAGS) clean))
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

maintainer-clean-local:
	-rm -rf dist/ ViennaRNA.egg-info

distclean-local:
	-rm -f pyproject.toml setup.py setup.cfg

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
