[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ViennaRNA"
version = "2.6.4"
description = "A library for the prediction and comparison of RNA secondary structures."
authors = [
  { name = "Ronny Lorenz", email = "ronny@tbi.univie.ac.at" },
  { name = "Ivo L. Hofacker", email = "ivo@tbi.univie.ac.at" },
]
maintainers = [
  { name = "Ronny Lorenz", email = "rna@tbi.univie.ac.at" },
  { name = "Ayaan Hossain", email = "auh57@psu.edu" },
]
requires-python = ">=3.8"
license = {file = "COPYING"}
keywords = [
        'synthetic',
        'computational',
        'biology',
        'genetic',
        'DNA',
        'RNA',
        'secondary',
        'structure',
        'prediction',
        'minimum',
        'free',
        'energy',
        'centroid',
        'subopt',
        'mfe',
        'ViennaRNA',
        'dynamic',
        'partition function',
        'modified base',
        'constraints',
        'programming']

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
]

dynamic = ["readme"]

[project.urls]
Homepage = "https://www.tbi.univie.ac.at/RNA"
Documentation = "https://viennarna.readthedocs.io/"
"Bug Tracker" = "https://github.com/ViennaRNA/ViennaRNA/issues"
Changelog = "https://www.tbi.univie.ac.at/RNA/changelog.html"

[tool.setuptools.package-dir]
RNA = "interfaces/Python/RNA"
ViennaRNA = "interfaces/Python/ViennaRNA"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -v"
testpaths = ["tests/python"]

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"
